homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:

device_tracker:
  - platform: eero_tracker
    consider_home: 300
    interval_seconds: 60
    only_macs: "34:08:BC:12:62:D8"
  - platform: hue_custom

weather:
  - platform: darksky
    name: Hourly Forecast
    api_key: !secret dark_sky_api_key
  - platform: darksky
    name: Daily Forecast
    api_key: !secret dark_sky_api_key
    mode: daily

google:
  client_id: !secret google_cal_client_id
  client_secret: !secret google_cal_client_secret
  
speedtestdotnet:
  server_id: 8864

discovery:
logger:
  default: info
ios:
hue:

custom_updater:
  card_urls:
   - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json
  component_urls:
   - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json   

ifttt:
  key: !secret ifttt_key

influxdb:
  host: influxdb
  port: 8086
  database: !secret influx_db
  username: !secret influx_username
  password: !secret influx_pw
  max_retries: 3
  default_measurement: state

panel_iframe:
  # nodered:
  #   title: Node-RED
  #   icon: mdi:sitemap
  #   url: https://192.168.7.163:1880
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://192.168.7.167:8888
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.7.167:3000

# binary_sensor:
#   - platform: hue_custom

sensor: !include_dir_merge_list sensor
group: !include_dir_merge_list group
automation: !include automations.yaml
script: !include_dir_merge_list script
